#!/bin/bash
# $Id: chklnks,v 1.15 2016/04/18 11:55:41 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/chklnks,v $
# $Revision: 1.15 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
syntax="$cmd [-d] [-v]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-a) all=1;shift;;
		-d) set -x;debug=:;shift;;
		-r) action=delete;shift;;
		-v) verbose=0;shift;;
		-V) echo "$cmd $Revision: 1.15 $ $Date: 2016/04/18 11:55:41 $"|awk '{print $1,$3,$6}';exit;;  
		 /*) path="$path $1";shift;;
	esac
done
action=${action:-"echo"}
all=${all:=0}
if [ $all -eq 1 ];then
	path=`df -l|
		awk '! /Filesystem/{
			# Put local file systems mount points in array
			fss[NR]=$6
		}END{
			while (getline < "/proc/mounts"){
				# get mount options
				split($4,r,",")
				m[$2] = r[1] 
			}
			for (fs in fss){
				# use mount point as index into arrays 
				if (m[fss[fs]] ~ /rw/ ){
					printf fss[fs]" "
				}
			}
		}'
	`
fi
path=${path:-"./"}
echo $path
for d in $path;do
	if [ $verbose ];then
		echo "$cmd: checking directory $d"
	fi
	sudo find -L $d -xdev -type l -print|
	while read f ;do
		if [ $action == "delete" ];then
			if rm $f 2>/dev/null ;then 
				if [ $verbose ];then
					echo "$cmd: $f dead link removed" >&2
				fi
			else
				echo "$cmd: could not remove $f" >&2
			fi
		else
			$action "$cmd: found dead link $f" >&2
		fi
	done
done
