#!/bin/bash
# $Id: chklnks,v 1.9 2016/04/14 11:09:07 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/chklnks,v $
# $Revision: 1.9 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
syntax="$cmd [-d] [-v]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=:;shift;;
		-r) action=delete;shift;;
		-v) verbose=0;shift;;
		 *) path=$1;shift;;
	esac
done
action=${action:-"echo"}
path=${path:-"./"}
sudo find -L $path -type l -print|
while read f ;do
	if [ $action == "delete" ];then
		if rm $f ;then 
			if [ $verbose ];then
				echo "$cmd: $f dead link removed" >&2
			fi
		else
			echo "$cmd: could not remove $f" >&2
		fi
	else
			$action "$cmd: found dead link $f" >&2
	fi
done
