#!/bin/bash
# $Id: chklnks,v 1.38 2016/04/18 16:10:33 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/chklnks,v $
# $Revision: 1.38 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
syntax="$cmd [-a] [-d] [-h <hostid> [-r] [-v] [<dir_name> <dir_name> ....]|[-V]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-a) all=1;shift;;
		-d) set -x;debug=:;shift;;
		-h) hostid=$2;shift 2;;
		-r) action=delete;shift;;
		-v) verbose=0;shift;;
		-V) echo "$cmd $Revision: 1.38 $ $Date: 2016/04/18 16:10:33 $"|awk '{print $1,$3,$6}';exit;;  
		 /*) path="$path $1";shift;;
	esac
done
action=${action:-"echo"}
all=${all:=0}
verbose=${verbose:-1}
if [ "$hostid" ]; then
	if nc -zw 2 $hostid 22 ;then
		rchk="ssh $hostid"
	else	
		echo "$cmd: ssh not available on $hostid" >&2
		exit 1
	fi
fi
		
if [ $all -eq 1 ];then
	path=`$rchk df -l|
		awk '! /Filesystem/{
			# Put local file systems mount points in array
			fss[NR]=$6
		}END{
			while ( getline < "/proc/mounts" ){
				# get mount options
				split($4,r,",")
				m[$2] = r[1] 
			}
			for (fs in fss){
				print fs
				# use mount point as index into arrays 
				if (m[fss[fs]] ~ /rw/ ){
					printf fss[fs]" "
				}
			}
		}'
	`
fi
path=${path:-"./"}
[ "$verbose" ] &&{
	echo "$cmd: paths = "$path
}
exit
for d in $path;do
	if [ $verbose ];then
		echo "$cmd: checking directory $d"
	fi
	$rchk sudo find -L $d -xdev -type l -print |
	while read f ;do
		if [ $action == "delete" ];then
			if $rchk "rm $f 2>/dev/null" ;then 
				if [ $verbose ];then
					echo "$cmd: $f dead link removed" >&2
				fi
			else
				echo "$cmd: could not remove $f" >&2
			fi
		else
			$action "$cmd: found dead link $f" >&2
		fi
	done
done
